### PR TITLE
Fix `BufferedReader` error caused by opening an empty file in S3 in "rb" mode

### LINKED ISSUE #269: `ValueError: buffer size must be strictly positive` when opening an empty file in S3 with "rb" mode
In case we try to open an empty (zero-bytes) file on S3 in "rb" mode using pfio v2 API with the default buffering option, we get this error.
```python
>>> import pfio; pfio.__version__
'2.2.0'
>>> with pfio.v2.open_url('s3://<bucket>/empty_file.dat', 'rb') as f:
...     pass
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.8/site-packages/pfio/v2/fs.py", line 310, in open_url
    with fs.open(filename, mode) as fp:
  File "/usr/local/lib/python3.8/site-packages/pfio/v2/s3.py", line 407, in open
    obj = io.BufferedReader(obj, buffer_size=bs)
ValueError: buffer size must be strictly positive
```

This is because
https://github.com/pfnet/pfio/blob/2.2.0/pfio/v2/s3.py#L401-L407
```python
    bs = min(obj.content_length, DEFAULT_MAX_BUFFER_SIZE)
```
this will make `bs` to be zero, which is then passed to `BufferedReader` as the buffer size causing the error.

In case the content length of the object to be read is zero, we of course don't need buffering at all, so I think we can simply skip wrapping `obj` by `BufferedReader`.

### PR DESCRIPTION
**Pull request by belltailjp**
Fixes #269

### CODE REVIEW

**Review by kuenishi — APPROVED** [review]
Good catch and looks good to me. @belltailjp Do you think you want a 2.2.1 release for this fix?

**Comment by belltailjp** [comment]
To me it's not actually urgent, because in my current workload specifically, empty files being created itself, maybe due to an unknown bug in my code or libraries, is problematic (eventually causes of another error).
So I guess the release timing can be relatively flexible (of course making a release now is also super fine!).

**Comment by kuenishi** [comment]
Thanks for the details. For now, I'll put this for 2.3 schedule, until other issues in high priority come.

**Pull request merged**
